name: Tests

on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  TRANSFORMERS_IS_CI: yes

jobs:

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: pip

    - uses: pre-commit/action@v3.0.1
      env:
        SKIP: no-commit-to-branch


  pytest:
    name: PyTest
    runs-on: ubuntu-latest
    needs: [pre-commit]

    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.11']
        pytorch_version: [2.5.1, 2.6.0, 2.7.1]

    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        cache: pip

    - name: Upgrade pip
      run: |
        pip install --upgrade pip
        pip install --upgrade packaging==23.2 setuptools==75.8.0 wheel

    - name: Install PyTorch
      run: |
        pip install torch==${{ matrix.pytorch_version }}

    - name: Install dependencies
      run: |
        pip show torch
        pip install --no-build-isolation -U -e .
        python scripts/unsloth_install.py | sh
        python scripts/cutcrossentropy_install.py | sh
        pip install -r requirements-dev.txt -r requirements-tests.txt

    - name: Validate PyTorch version
      run: |
        python -c "import torch; assert '${{ matrix.pytorch_version }}' in torch.__version__"

    - name: Validate CLI
      run: |
        axolotl --help

    - name: Run tests
      run: |
        pytest -v -n8 --dist loadfile \
          --ignore=tests/e2e/ \
          --ignore=tests/patched/ \
          --ignore=tests/cli/ \
          tests/ \
          --cov=axolotl \
          --cov-report=xml


  pytest-sdist:
    name: PyTest from Source Dist
    runs-on: ubuntu-latest
    needs: [pre-commit]

    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.11']
        pytorch_version: [2.5.1, 2.6.0]

    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        cache: pip

    - name: Upgrade pip
      run: |
        pip install --upgrade pip
        pip install --upgrade packaging==23.2 setuptools==75.8.0 setuptools_scm build wheel

    - name: Install PyTorch
      run: |
        pip install torch==${{ matrix.pytorch_version }}

    - name: Build and install sdist
      run: |
        python -m build --no-isolation --sdist
        pip install --no-build-isolation dist/axolotl*.tar.gz

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt -r requirements-tests.txt

    - name: Validate CLI
      run: |
        axolotl --help

    - name: Run tests
      run: |-
        pytest -v -n8 --dist loadfile \
          --ignore=tests/e2e/ \
          --ignore=tests/patched/ \
          --ignore=tests/cli/ \
          tests/

        pytest -v tests/patched/
        pytest -v tests/cli/
